### ISSUE TITLE
Refactor misuses of css modules (ex: match.css)

### ISSUE THREAD

**Issue by mike-robertson** [odota/ui#314]
We shouldn't be having multiple components importing the same css files. It overrides one of the primary benefits of css-modules (locally scoped css names), and it is overall harder to figure out what styles belong to what (making refactoring css in general a PITA). Instead, we should have separate files for each component, and if they reuse a class, properly utilize the composes syntax:

``` css
.thing {
  composes: thing from "./Match.css";
}
```
