### ISSUE TITLE
A couple of post redesign eye-stabbers

### ISSUE THREAD

**Issue by ivanpepelko** [odota/ui#425]
The first thing I noticed:
![screenshot_20161107_082306](https://cloud.githubusercontent.com/assets/7328461/20049460/8443aeac-a4c3-11e6-84fb-551a890850be.png)

Possible fix:
```css
.HeroImage__playerSlot {
  /* ... */
  top: 10px;
}
```

Also this:
![screenshot_20161107_082230](https://cloud.githubusercontent.com/assets/7328461/20049473/99ae6872-a4c3-11e6-8260-ce7ac0775d26.png)

Firefox 49, 2560x1440 monitor.
